CC = gcc
CFLAGS=-Wall -Wextra
TARGET=SimpleCache

# $(CC) $(CFLAGS) SimpleProgram.c SimpleCache.c -o $(TARGET)
all:
	$(CC) $(CFLAGS) ../tests/test_tasks.c ../task3/2_way_set_associative.c -o $(TARGET)

clean:
	rm $(TARGET)